### ISSUE TITLE
Plugin malfunctioning on Ubuntu Linux (22.04) when installed on NFS since plugin version 2.0.0

### ISSUE THREAD

**Issue by kammoji** [rage/tmc-vscode#726]
**Describe the bug**
The VScode plugin doesn't load on Ubuntu 22.04 when the host's home directories are NFS mounts. The error message is:

`[2024-09-27 14:31:23:454] [ERROR] Error during initialization: Runtime Error: Failed to lock file at path /home/********/.config/tmc-vscode_plugin/config.toml`

I did a quick check of this and it looks like that plugin versions 1.3.4+ all have issues in acquiring the file locks in an NFS system.

**To Reproduce**
1. Login to the Ubuntu 22.04 host where ~ is an NFS mount. NOTE! If you're in Helsinki University, our "Cubbli Linux" VMware remote desktop will apply here!
2. Launch VScode, load plugin version 3.0.4 (latest at the time of this writing)
3. Observe error log.

**Expected behavior**
Plugin loads and shows user profile options if logged and a login window if not logged in

**Screenshots**
I'm happy to share these privately if needed.

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04, kernel version: 5.15.0-122-generic
 - VSCode Version 1.93.1
 - TMC Extension Version 3.0.4
 - Other extensions: Python: v2024.14.1, Extension Pack for Java v0.29.0, Maven for Java v0.44.0

**TMC Extension logs**
I'm happy to share these privately if needed.

**Additional context**
Issue can be circumvented by downgrading the plugin to version 1.3.4 or possibly earlier. Probably also changing the plugin install dir to a non-NFS could help here but e.g. in our Helsinki University remote desktop there's no such dir available to a standard user.

**Comment by Heliozoa** [comment]
Sorry for not getting to this issue sooner. This should be fixed in the latest version.

**Comment by kammoji** [comment]
Hi @Heliozoa,

Thanks for your reply. I went ahead and upgraded the TMC plugin to 3.1.0 in our standard Cubbli 22.04 VScode environment (Desktop is the same as in the previous message to this thread). The plugin started auto-migrating my exercises (I'm taking the course Data Analysis with Python right now). Unfortunately, at the end of this process I'm greeted with the pop-up error: "TestMyCode initialization failed: Error: Exercise migration failed." in VScode.

I'm seeing a lot of entries like this in the VScode console:

`[2025-01-24 13:40:30:718] [ERROR] Migration failed for exercise mooc-data-analysis-with-python-2024-2025/part04-e17_cleaning_data:
Runtime Error — Directory /home/MY_USERNAME/.local/share/tmc/vscode/mooc-data-analysis-with-python-2024-2025/part04-e17_cleaning_data already exists — Runtime Error: Directory /home/MY_USERNAME/.local/share/tmc/vscode/mooc-data-analysis-with-python-2024-2025/part04-e17_cleaning_data already exists`

Downgrading the plugin back to the previous version to 1.3.4 doesn't really work anymore, it cannot find my exercise files anymore since evidently the files have been migrated.

I'm happy to provide a full console output privately if this would be helpful to resolve this and we find a proper channel for it here in Github or elsewhere.

**Comment by kammoji** [comment]
Hi @Heliozoa ,

Thanks for the reply and sorry for the delay in response whilst I tested with your latest instructions. But I'm happy to tell you that with the latest 3.2.0 the plugin now work. Thanks for your help! What I did:

1. Updated to 3.2.0: No effect, so the error in migrating still happened accompanied with the problem in extension init.
2. Completely uninstalled the TMC plugin, then re-installed with version 3.2.0 and re-started extensions: No effect, the issue persisted.
3. Uninstalled the TMC plugin, exited the VScode app, then re-launched VScode and installed TMC plugin version 3.2.0: **It now works and I'm able to access and re-download my exercises.**

With that, I'm closing the issue. Keep up the Good Work :) !
